name: test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.7.1=h63175ca_0
  - arosics=1.10.1=py311h1ea47a8_0
  - attrs=23.2.0=pyh71513ae_0
  - aws-c-auth=0.7.16=hec1de76_6
  - aws-c-cal=0.6.10=hd481e46_1
  - aws-c-common=0.9.13=hcfcfb64_0
  - aws-c-compression=0.2.18=hd481e46_1
  - aws-c-event-stream=0.4.2=h0f06f08_4
  - aws-c-http=0.8.1=hdb5aac5_5
  - aws-c-io=0.14.5=h08270f9_1
  - aws-c-mqtt=0.10.2=hfea8755_4
  - aws-c-s3=0.5.2=h4b2095a_0
  - aws-c-sdkutils=0.1.15=hd481e46_1
  - aws-checksums=0.1.18=hd481e46_1
  - aws-crt-cpp=0.26.2=h8492d2a_7
  - aws-sdk-cpp=1.11.267=h93f5800_1
  - azure-core-cpp=1.11.1=h249a519_1
  - azure-storage-blobs-cpp=12.10.0=h91493d7_1
  - azure-storage-common-cpp=12.5.0=h91493d7_4
  - bleach=6.1.0=pyhd8ed1ab_0
  - blosc=1.21.5=hdccc3a2_0
  - bokeh=3.3.4=pyhd8ed1ab_0
  - branca=0.7.1=pyhd8ed1ab_0
  - brotli=1.1.0=hcfcfb64_1
  - brotli-bin=1.1.0=hcfcfb64_1
  - brotli-python=1.1.0=py311h12c1d0e_1
  - bzip2=1.0.8=h2bbff1b_5
  - c-ares=1.27.0=hcfcfb64_0
  - c-blosc2=2.13.2=h183a6f4_0
  - ca-certificates=2024.2.2=h56e8100_0
  - cairo=1.18.0=h1fef639_0
  - cartopy=0.22.0=py311hf63dbb6_1
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cfitsio=4.3.1=h9b0cee5_0
  - charls=2.4.2=h1537add_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=win_pyh7428d3b_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - cmocean=3.1.3=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - colorcet=3.1.0=pyhd8ed1ab_0
  - colorspacious=1.1.2=pyh24bf2e0_0
  - contourpy=1.2.0=py311h005e61a_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - dav1d=1.2.1=hcfcfb64_0
  - dill=0.3.8=pyhd8ed1ab_0
  - expat=2.6.1=h63175ca_0
  - fftw=3.3.10=nompi_h38027f0_108
  - fiona=1.9.6=py311hbcf8545_0
  - fmt=10.2.1=h181d51b_0
  - folium=0.16.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=hbde0cde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.49.0=py311ha68e1ae_0
  - freetype=2.12.1=hdaf720e_2
  - freexl=2.0.0=h8276f4a_0
  - gdal=3.8.4=py311h21a6730_2
  - geoarray=0.17.2=py311h1ea47a8_0
  - geojson=3.1.0=pyhd8ed1ab_0
  - geopandas=0.14.3=pyhd8ed1ab_0
  - geopandas-base=0.14.3=pyha770c72_0
  - geos=3.12.1=h1537add_0
  - geotiff=1.7.1=hbf5ca3a_15
  - gettext=0.21.1=h5728263_0
  - giflib=5.2.1=h64bf75a_3
  - hdf4=4.2.15=h5557f11_7
  - hdf5=1.14.3=nompi_h73e8ff5_100
  - holoviews=1.18.3=pyhd8ed1ab_0
  - icu=73.2=h63175ca_0
  - idna=3.6=pyhd8ed1ab_0
  - imagecodecs=2024.1.1=py311h71c7c69_2
  - imageio=2.34.0=pyh4b66e23_0
  - importlib-metadata=7.0.2=pyha770c72_0
  - intel-openmp=2024.0.0=h57928b3_49841
  - jinja2=3.1.3=pyhd8ed1ab_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jxrlib=1.1=hcfcfb64_3
  - kealib=1.5.3=hd248416_0
  - kiwisolver=1.4.5=py311h005e61a_1
  - krb5=1.21.2=heb0366b_0
  - lazy_loader=0.3=pyhd8ed1ab_0
  - lcms2=2.16=h67d730c_0
  - lerc=4.0.0=h63175ca_0
  - libabseil=20240116.1=cxx17_h63175ca_2
  - libaec=1.1.2=h63175ca_1
  - libarchive=3.7.2=h313118b_1
  - libavif=1.0.1=h7a9aacb_3
  - libblas=3.9.0=21_win64_mkl
  - libboost-headers=1.84.0=h57928b3_1
  - libbrotlicommon=1.1.0=hcfcfb64_1
  - libbrotlidec=1.1.0=hcfcfb64_1
  - libbrotlienc=1.1.0=hcfcfb64_1
  - libcblas=3.9.0=21_win64_mkl
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.5.0=hd5e4a3a_0
  - libdeflate=1.19=hcfcfb64_0
  - libexpat=2.6.1=h63175ca_0
  - libffi=3.4.4=hd77b12b_0
  - libgdal=3.8.4=hc9eed96_2
  - libglib=2.78.4=h39d0aa6_4
  - libgoogle-cloud=2.22.0=h9cad5c0_1
  - libgoogle-cloud-storage=2.22.0=hb581fae_1
  - libgrpc=1.62.1=h5273850_0
  - libhwloc=2.9.3=default_haede6df_1009
  - libiconv=1.17=hcfcfb64_2
  - libjpeg-turbo=3.0.0=hcfcfb64_1
  - libkml=1.3.0=haf3e7a6_1018
  - liblapack=3.9.0=21_win64_mkl
  - libnetcdf=4.9.2=nompi_h07c049d_113
  - libpng=1.6.43=h19919ed_0
  - libpq=16.2=hdb24f17_0
  - libprotobuf=4.25.3=h503648d_0
  - libre2-11=2023.09.01=hf8d8778_2
  - librttopo=1.1.0=h94c4f80_15
  - libspatialindex=1.9.3=h39d44d4_4
  - libspatialite=5.1.0=hf2f0abc_4
  - libsqlite=3.45.1=hcfcfb64_0
  - libssh2=1.11.0=h7dfc565_0
  - libtiff=4.6.0=h6e2ebb7_2
  - libwebp-base=1.3.2=hcfcfb64_0
  - libxcb=1.15=hcd874cb_0
  - libxml2=2.12.5=hc3477c8_0
  - libzip=1.10.1=h1d365fa_3
  - libzlib=1.2.13=hcfcfb64_5
  - libzopfli=1.0.3=h0e60522_0
  - linkify-it-py=2.0.3=pyhd8ed1ab_0
  - lz4-c=1.9.4=hcfcfb64_0
  - lzo=2.10=he774522_1000
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mapclassify=2.6.1=pyhd8ed1ab_0
  - markdown=3.5.2=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.5=py311ha68e1ae_0
  - matplotlib-base=3.8.3=py311h6e989c2_0
  - mdit-py-plugins=0.4.0=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - minizip=4.0.5=h5bed578_0
  - mkl=2024.0.0=h66d3029_49657
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - networkx=3.2.1=pyhd8ed1ab_0
  - numpy=1.26.4=py311h0b4df5a_0
  - openjpeg=2.5.2=h3d672ee_0
  - openssl=3.2.1=hcfcfb64_0
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=2.2.1=py311hf63dbb6_0
  - panel=1.3.8=pyhd8ed1ab_0
  - param=2.0.2=pyhca7485f_0
  - pcre2=10.43=h17e33f8_0
  - pillow=10.2.0=py311h4dd8a23_0
  - pip=23.3.1=py311haa95532_0
  - pixman=0.43.4=h63175ca_0
  - plotly=5.19.0=pyhd8ed1ab_0
  - poppler=24.03.0=hc2f3c52_0
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=16.2=h1beaf6b_0
  - proj=9.3.1=he13c7e8_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - py-tools-ds=0.21.1=py311h1ea47a8_1
  - pyfftw=0.13.1=py311he023d06_0
  - pykrige=1.7.1=py311h59ca53f_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pyproj=3.6.1=py311h82130bc_5
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.11.8=h2628c8c_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.11=4_cp311
  - pytz=2024.1=pyhd8ed1ab_0
  - pyviz_comms=3.0.1=pyhd8ed1ab_0
  - pywavelets=1.4.1=py311h59ca53f_1
  - pyyaml=6.0.1=py311ha68e1ae_1
  - rav1e=0.6.6=h975169c_2
  - re2=2023.09.01=hd3b24a8_2
  - requests=2.31.0=pyhd8ed1ab_0
  - rtree=1.2.0=py311hcacb13a_0
  - scikit-image=0.22.0=py311hf63dbb6_2
  - scikit-learn=1.4.1.post1=py311h142b183_0
  - scipy=1.12.0=py311h0b4df5a_2
  - setuptools=68.2.2=py311haa95532_0
  - shapely=2.0.3=py311h16bee0b_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=hfb803bf_0
  - spdlog=1.12.0=h64d2f7d_2
  - spectral=0.23.1=pyh1a96a4e_0
  - sqlite=3.41.2=h2bbff1b_0
  - svt-av1=1.7.0=h63175ca_0
  - tbb=2021.11.0=h91493d7_1
  - tenacity=8.2.3=pyhd8ed1ab_0
  - threadpoolctl=3.3.0=pyhc1e730c_0
  - tifffile=2024.2.12=pyhd8ed1ab_0
  - tiledb=2.20.1=hb65f977_3
  - tk=8.6.13=h5226925_1
  - tornado=6.4=py311ha68e1ae_0
  - tqdm=4.66.2=pyhd8ed1ab_0
  - typing_extensions=4.10.0=pyha770c72_0
  - tzdata=2024a=h04d1e81_0
  - uc-micro-py=1.0.3=pyhd8ed1ab_0
  - ucrt=10.0.22621.0=h57928b3_0
  - uriparser=0.9.7=h1537add_1
  - urllib3=2.2.1=pyhd8ed1ab_0
  - vc=14.2=h21ff451_1
  - vc14_runtime=14.38.33130=h82b7239_18
  - vs2015_runtime=14.38.33130=hcb4865c_18
  - webencodings=0.5.1=pyhd8ed1ab_2
  - wheel=0.41.2=py311haa95532_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - xerces-c=3.2.5=h63175ca_0
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xyzservices=2023.10.1=pyhd8ed1ab_0
  - xz=5.4.6=h8cc25b3_0
  - yaml=0.2.5=h8ffe710_2
  - zfp=1.0.1=h63175ca_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hcfcfb64_5
  - zlib-ng=2.0.7=hcfcfb64_0
  - zstd=1.5.5=h12be248_0
  - pip:
      - affine==2.4.0
      - rasterio==1.3.9
      - snuggs==1.4.7
prefix: C:\Users\tulet\miniconda3\envs\test_env
